import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import AuthProvider from '@/providers/AuthProvider';
import { getServerSession } from 'next-auth';
import { options } from '../api/auth/[...nextauth]/options';
import { redirect } from 'next/navigation';

const poppins = Poppins({ weight: '400', subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options);
  if(session){
    redirect('/home');
  }

  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  )
}
