export type TuserSchema={
    _id:string,
    name?:string,
    email?:string,
    twitterId?:string,
    provider?:string,
    isVerified?:boolean,
    password?:string,
    location?:string,
    profile_image?:string,
    banner_image?:string,
    bio?:string,
    birthday?:Date,
    followers?:string,
    following?:string,
    follower_count?:number,
    following_count?:number,
    role?:string,
    tweets?:[string],
    liked_tweet?:[string],
    user_type?:string,
    saved_tweet?:[string],
    comment_tweets?:[string],
    createdTime?:string,
    createdAt?:Date
}


export type Tprofile = {
    _id:string,
    name:string,
    twitterId:string,
    location:string,
    profile_image:string,
    banner_image:string,
    bio:string,
    birthday:string,
    followers:number,
    following:number,
    createdTime:string,
    tweets?:Array<string>,
}