import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/providers/AuthProvider';
import {QueryClient ,QueryClientProvider} from '@tanstack/react-query'

const poppins = Poppins({ weight: '400', subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <QueryClientProvider client={queryClient}>
          {children}
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
